### ISSUE TITLE
ambix won't compile with gcc 6.2.1

### ISSUE THREAD

**Issue by yetyetanotherusername** [kronihias/ambix#12]
There seems to be a problem with JUCE and gcc 6, see https://www.bountysource.com/issues/34084030-can-t-compile-in-arch-64bit-solved-reverting-to-gcc-5-3-won-t-compile-with-gcc-6-1-1

If the redundant definition of `lround` is commented out in lpc_flac.c, it will compile.

```
gcc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)
```

As far as i understand, this problem has been resolved in JUCE, so maybe updating JUCE in ambix will fix this issue.

**Comment by kronihias** [comment]
thanks, i updated to the latest juce version, please check again.

**Comment by yetyetanotherusername** [comment]
This issue is fixed, i can compile without errors now
