### ISSUE TITLE
Compile standalone and plugins in Debian Linux stretch.

### ISSUE THREAD

**Issue by ritsch** [kronihias/ambix#13]
Hello,

Last month I managed to compile ambix both on Debian stable and used it in a concert quite well.
(not extensivly testing) but binaural-decoder, decoder and also encoder with GUI on testing (see script I used on various machines) using jack. (also decoder as vst does not work, but standalone)

Debian Strech: 
  - Switch back to c++ gnu version 5, since 6 is now didnt compile
  -  libeigen downgrade

Now I compiled again: (after a git pull)
   now it compiles also using gcc-6, good,but
   - standalone programs does not have  the right number of jack channels, always 12 ?
   - lv2 fails to initiate on loading
   - vst crashes

What was the change ? only the juce library update 
  Any hints ?

Appendix:
  FYI,  script to build ambix on debian::

[try_to_make_ambix-on-debian.sh.txt](https://github.com/kronihias/ambix/files/632233/try_to_make_ambix-on-debian.sh.txt)

**Comment by ritsch** [comment]
Found the error for wrong jack channel numbers: have to apply the patch in JUCE now manually before Build.

Is this correct ?

**Comment by kronihias** [comment]
Hi @ritsch ,
thanks for your feedback!

The last commits included an update to the new version of JUCE, yes. I did not do a proper crosscheck whether things still work under Linux with the new JUCE version.

Regarding the standalone version you are correct, I did not update the jack patch. I did this now and the standalone version works fine.

Regarding LV2 and VST I guess things might be more complicated. I quickly tried the VST versions with Ardour5 and the GUI seems to crash Ardour. However, with Carla they work...

Did you find out something already?

**Comment by ritsch** [comment]
Thanks for fast response.

I will do tests on linux next week for a project using ardour5 but first 'lv2_jack_host'
and report. 

Is the jack pacth needed or should I try to get same behaviour without patching JUCE ?

**Comment by kronihias** [comment]
patching juce_linux_JackAudio.cpp is needed, otherwise the standalone versions have a wrong input/output channel count.
(JUCE will only create the number of physical input/output channels of the soundcard, which makes no sense for JACK.)

I did raise this in the forum long time ago: 
https://forum.juce.com/t/jackaudioiodevice-input-output-channel-count/10384
