### ISSUE TITLE
cmake does not include fftw3 in MSVS2015 project

### ISSUE THREAD

**Issue by yetyetanotherusername** [kronihias/ambix#15]
Generating a Visual Studio2015 project file with cmake will result in a project where the fftw directory is not contained in the additional include directories of the solutions for the plugins that require fftw.

cmake does not throw any error messages.

![capture](https://cloud.githubusercontent.com/assets/15213889/24829475/a5010b9a-1c72-11e7-85f4-2b2e85e40551.PNG)

**Comment by kronihias** [comment]
thanks for the report.
please try again @yetyetanotherusername , should be fixed now

**Comment by yetyetanotherusername** [comment]
Works, thank you!
