### ISSUE TITLE
`make -j` fails

### ISSUE THREAD

**Issue by umlaeute** [kronihias/ambix#17]
it seems that the target dependencies of the generated makefile are not correct.
at least i get rather consistent build failures when doing parallel builds:

    make -j3

**Comment by umlaeute** [comment]
this is with the current HEAD 6ac2bb7

**Comment by kronihias** [comment]
the dependency should be fixed now in the Cmake project with commit 3464c6b48cff82631927ec612aef7550fe1494d4
