### ISSUE TITLE
Semicolon missing in juce_StandaloneFilterWindow.h

### ISSUE THREAD

**Issue by ritsch** [kronihias/ambix#2]
Hallo Matthias,

da ich gerade auf linux teste.

Sandalone kompilieren geht ganz gut und seit deinem commit auch das standalone binaural rendering, wenn auch noch knackser drin sind (denke aber von den filesets).

Allerdings musste ich das ändern:

diff --git a/JUCE/standalone-filter/juce_StandaloneFilterWindow.h b/JUCE/standalone-filter/juce_StandaloneFilterWindow.h
index a9d7867..e53b877 100755
--- a/JUCE/standalone-filter/juce_StandaloneFilterWindow.h
+++ b/JUCE/standalone-filter/juce_StandaloneFilterWindow.h
@@ -62,7 +62,7 @@ public:
 
         if (filter == nullptr)
         {
-            jassertfalse    // Your filter didn't create correctly! In a standalone app that's not too great.
+            jassertfalse;    // Your filter didn't create correctly! In a standalone app that's not too great.^M
             JUCEApplication::quit();
         }

Weiss nicht warum es überhaupt gibt, bei meinen JUCE ist das unter
 ./modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h

mfG
 winfried

**Comment by kronihias** [comment]
Hallo Winfried,

danke für den Hinweis! Ist korrigiert.

Grüße, Matthias
