### ISSUE TITLE
Binaural decoder channels

### ISSUE THREAD

**Issue by michalziobro** [kronihias/ambix#22]
Maybe I'm missing something important but... why is the output from binaural plugin multichannel? Shouldn't it be only stereo for headphones playback?

**Comment by kronihias** [comment]
Hi, yes you miss something important: what are you testing? vst plugin? win/mac/linux? what host?
In Reaper under Windows ambix_binaural has 2 output channels, as expected.
Best,
Matthias

**Comment by kronihias** [comment]
closing this since there is no bug.
