### ISSUE TITLE
zita-convolver 4.0.0 compatibility

### ISSUE THREAD

**Issue by dvzrv** [kronihias/ambix#23]
[zita-convolver 4.0.0](https://kokkinizita.linuxaudio.org/linuxaudio/downloads/zita-convolver-4.0.0.tar.bz2) has been released the beginning of June.
I have upgraded [community] on Arch Linux [to this version](https://www.archlinux.org/packages/community/x86_64/zita-convolver/) (to rebuild other packages against it), but ambix is sadly not yet compatible.

It would be very awesome to get compatibility, so I can move ambix to [community], too.

**Comment by kronihias** [comment]
Thanks @lkoenig, maybe @dvzrv you could test if this works for you?

**Comment by dvzrv** [comment]
Thank you! This works. I'm successfully using this with the latest release :)
