### ISSUE TITLE
Compilation fails on Linux Mint 18.2 x64

### ISSUE THREAD

**Issue by chris-kuhr** [kronihias/ambix#25]
Hi *,

compiling result in the following error:

`
        /home/christoph/ambix.git/ambix_binaural/Source/MtxConv.cpp: In constructor 'MtxConvMaster::MtxConvMaster()’:
        /home/christoph/ambix.git/ambix_binaural/Source/MtxConv.cpp:47:36: error: ‘fftwf_make_planner_thread_safe’ was not declared in this scope
        fftwf_make_planner_thread_safe(); // this works since fftw-3.3.6-pl2
`
I have installed the dependencies with the provided command of the readme file.
I am running Linux Mint 18.2 Sonya 64-bit with Kernel Linux 4.8.0-53-generic x86_64.

Any advice?

BR,
Ck

**Comment by chris-kuhr** [comment]
any suggestions?
is the code still maintained?

**Comment by magnetophon** [comment]
Ther's some suggestions here: https://github.com/kronihias/ambix/issues/21

**Comment by chris-kuhr** [comment]
I have installed fttw3 3.3.8 and manually linked both variants against `fttw3` and `fttw3_threads`.
But I still cannot compile ambix_binaural:

```
CMakeFiles/ambix_binaural_standalone_o5.dir/__/Source/MtxConv.cpp.o: In function `MtxConvMaster::MtxConvMaster()':
MtxConv.cpp:(.text+0x63f): undefined reference to `fftwf_make_planner_thread_safe'
CMakeFiles/ambix_binaural_standalone_o5.dir/__/Source/PluginProcessor.cpp.o: In function `Ambix_binauralAudioProcessor::LoadConfiguration(juce::File)':
PluginProcessor.cpp:(.text+0x6426): undefined reference to `Convproc::configure(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, float)'
PluginProcessor.cpp:(.text+0x6483): undefined reference to `Convproc::impdata_create(unsigned int, unsigned int, int, float*, int, int)'
collect2: error: ld returned 1 exit status
ambix_binaural/ambix_binaural_standalone/CMakeFiles/ambix_binaural_standalone_o5.dir/build.make:319: recipe for target '_bin/standalone/ambix_binaural_standalone_o5' failed
make[2]: *** [_bin/standalone/ambix_binaural_standalone_o5] Error 1
CMakeFiles/Makefile2:216: recipe for target 'ambix_binaural/ambix_binaural_standalone/CMakeFiles/ambix_binaural_standalone_o5.dir/all' failed
make[1]: *** [ambix_binaural/ambix_binaural_standalone/CMakeFiles/ambix_binaural_standalone_o5.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Any further suggestions?

Thanks,
Ck

**Comment by magnetophon** [comment]
I suggest asking in the other issue, and closing this one.
You'll have more eyes on it that way.
