### ISSUE TITLE
v0.3.0 Native Apple Silicon installer failed

### ISSUE THREAD

**Issue by jwmao98** [kronihias/ambix#36]
Hello! I've been trying to install the plugins using the pre-built installer and have got the dependencies (`MacPorts`, `eigen3`) installed on my Mac.

After running the installer, it returned an error message of failed installation; weirdly enough, only the `ambix_binaural` plugin is successfully copied to the plugin folder and can be opened and used in Reaper.

Is there anything I could test to see if this issue persists?

**Comment by kronihias** [comment]
Hi!

For the pre-built installer there are no dependencies, you only need eigen3 if you want to compile the plugins yourself.

What did the error message say?

What macOS are you using?

**Comment by jwmao98** [comment]
Thanks for the quick response! I'm using a MacBook Pro (M1 Pro chip) with Ventura 13.6.4.

The error message was very generic: "The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

I suspect the issue has something to do with a problematic installation of `eigen3` using `MacPorts`. I have reinstalled the command line tool to Xcode using `xcode-select --install` but it doesn't seem to be enough.

**Comment by kronihias** [comment]
Not xcode nor any other dependency are necessary for installing the release installers: https://github.com/kronihias/ambix/releases

Just as cross check, does the installer for https://github.com/kronihias/mcfx/releases work?

**Comment by realshafer** [comment]
I'm also getting the generic error during installation of ambix o1, o3, or o5: "The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance." I'm not sure if this helps, but clicking "Customize" shows VST, action = "upgrade," and size = 0KB. Kind of odd since this is a fresh installation.

**Comment by kronihias** [comment]
HI @jwmao98 and @realshafer , I just updated the mac os installers for ambix and mcfx, I hope they work for you now.
https://github.com/kronihias/ambix/releases
https://github.com/kronihias/mcfx/releases
Please test again and let me know.

**Comment by realshafer** [comment]
Wonderful! Works as expected. Plugins installed. Thank you for the quick fix!
