### ISSUE TITLE
wrapping slider without patching JUCE

### ISSUE THREAD

**Issue by umlaeute** [kronihias/ambix#8]
[here's a naive implementation](https://gist.github.com/umlaeute/04b67ab124bf1877fcef76ecc8527c3c) of a wrapping-slider that does not require patching of the JUCE sources.

it is implemented by hooking into the `SliderListener::valueChanged()` callback (and making the slider range slightly larger than needed).

so far this has only been tested on linux/standalone but here i haven't encountered eny problems.

given that the implementation was straight-forward i wonder why it wasn't done like this in the first place (or probably it *was* done like this at first but discarded for some reason)

**Comment by kronihias** [comment]
thanks for the patch! i included the changes slightly modified to allow slider dragging without wrapping which i prefer (getting the source exactly to -180° without editing the text).

the reason it wasn't done like this before was simply because i didn't realize it was that easy ;)

**Comment by umlaeute** [comment]
great that you like it :-)
